### ISSUE TITLE
Submit Button Broken 

### ISSUE THREAD

**Issue by lem0n4id** [lem0n4id/youtubeToMp3Converter#6]
### Describe the bug
[Submit button](https://github.com/lem0n4id/youtubeToMp3Converter/blob/cf54d5f8d059c6cb971ac3e853d3f992794c3730/templates/index.html#L11) doesn't work in index.html

### Possible fix-
add a button tag inside the anchor tag and enclose in in a form? 

I did this for the download button in music.html. 
check out this [commit](https://github.com/lem0n4id/youtubeToMp3Converter/commit/8cc7a3cd885891dea1011eb2d3f2efca1431941d)

**Comment by pspiagicw** [comment]
Done!

**Comment by lem0n4id** [comment]
Awesome work!
