### ISSUE TITLE
update href of the nav bar in about.html

### ISSUE THREAD

**Issue by lem0n4id** [lem0n4id/youtubeToMp3Converter#7]
https://github.com/lem0n4id/youtubeToMp3Converter/blob/cf54d5f8d059c6cb971ac3e853d3f992794c3730/templates/about.html#L18

https://github.com/lem0n4id/youtubeToMp3Converter/blob/cf54d5f8d059c6cb971ac3e853d3f992794c3730/templates/about.html#L21

**Comment by pspiagicw** [comment]
I added navbar to every page and it is defined in base.html , the url's are properly configured now
